apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-configmap
  namespace: kube-system
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        id: tetragon-log
        enabled: true
        paths:
          - /var/run/cilium/tetragon/*.log

    path.data: /usr/share/filebeat/data

    processors:
      - timestamp:
          field: "time"
          layouts:
            - '2006-01-02T15:04:05Z'
            - '2006-01-02T15:04:05.999Z'
            - '2006-01-02T15:04:05.999-07:00'
          test:
            - '2019-06-22T16:33:51Z'
            - '2019-11-18T04:59:51.123Z'
            - '2020-08-03T07:10:20.123456+02:00'

    setup.template.name: logs
    setup.template.pattern: "logs-cilium_tetragon.*"

    output.elasticsearch:
      hosts: ["http://elasticsearch.elastic.svc.cluster.local:9200"]
      username: "elastic"
      password: "ElasticPass123"
      index: logs-cilium_tetragon.log-default