apiVersion: v1
kind: Secret
metadata:
  name: elastalert2-secret
  namespace: elastic
type: Opaque
stringData:
  ELASTIC_USERNAME: "elastic"
  ELASTIC_PASSWORD: "ElasticPass123"

---
apiVersion: v1
kind: Secret
metadata:
  name: elastalert2-smtp-auth
  namespace: elastic
type: Opaque
stringData:
  smtp-auth.yaml: |
    user: "muhammadashir2004@gmail.com"
    password: "I-kept-my-google-app-password-here-for-gmail"